# Generated by Django 3.2 on 2021-05-01 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'curso', 'verbose_name_plural': 'cursos'},
        ),
    ]
